### PR TITLE
RFC-010: Synchronous Document Signing on a Remote Signing Service Provider using Long-Term Certificates and the EUDI Wallet

### PR DESCRIPTION
**Pull request by kerk12**
This Specification defines the procedures for using the EUDI wallet to digitally sign a document, using Long-Term certificates. It specifies a new protocol for executing digital signing, that will ensure successful communication and interoperability with the EUDI wallet and the Signing Service Providers, as well as Remote QES services.

### CODE REVIEW

**Review by lalc — APPROVED** [review]
Will merge to main and release it if there are no further objects from potential implementors

**Comment by gdegani** [comment]
Hi @lalc , do we have a deadline for suggesting changes to this RFC?

**Comment by lalc** [comment]
> Hi @lalc , do we have a deadline for suggesting changes to this RFC? 

I hope to get this merged within 15-November. You will still have time to raise issue before EWC RFC release 2.1. 

If there are obvious objections, you can of course do so now. 

cc: @kerk12 pls comment if you have project commitments etc to get this out on any specific deadline.

**Comment by endimion** [comment]
We should add section on how the issue the intial RQESAC before merging this to the main branch

**Review by andreasabr — APPROVED** [review]

**Pull request closed without merging**
